### ISSUE TITLE
Bad state: Future already completed

### ISSUE THREAD

**Issue by IzumiSagiri** [yegor-pelykh/coingecko_api#6] opened 2022-10-23 08:21 UTC
This error appears after connectTimeout passes. I did some research and found that this error is caused by Dio 4.0.6.

As for now, setting CoinGeckoApi client's connectTimeout to 0 could eliminate this error.

**Comment by yegor-pelykh** [comment] 2022-10-23 11:02
Thanks for the investigation!

Unfortunately, I do not know what can be done in this package now, given that the problem is in Dio package.
Let's wait for an acceptable fix from Dio community, and then adjust this package to use a working version.
For now, I would suggest using your workaround:
> Workaround:  **Please set CoinGeckoApi client's connectTimeout to 0.**

Thank you for your submission!

**Comment by yegor-pelykh** [comment] 2022-10-23 11:06
To track down the issue, I suggest following this thread:
https://github.com/flutterchina/dio/pull/1550

**Comment by yegor-pelykh** [comment] 2023-03-03 21:07
Fixed in `v1.1.1` by commit 28fd06373ea68c0223cb6e5dede112dfdee7fbce.

**Closed as completed by yegor-pelykh** 2023-03-03 21:07 UTC
Labels: dependency-issue, has-workaround
