### ISSUE TITLE
package is not installed

### ISSUE THREAD

**Issue by plibr** [yegor-pelykh/coingecko_api#1] opened 2021-11-20 07:28 UTC
```
$ flutter pub add coingecko_api
Because test >=1.17.11 <1.18.0 depends on test_api 0.4.3 and test >=1.18.0 <1.18.1 depends on test_api 0.4.4, test >=1.17.11 <1.18.1 requires test_api 0.4.3 or 0.4.4.
And because test >=1.18.1 <1.19.0 depends on test_api 0.4.5, test >=1.17.11 <1.19.0 requires test_api 0.4.3 or 0.4.4 or 0.4.5.
And because test >=1.19.0 <1.19.3 depends on test_api 0.4.6 and test >=1.19.3 depends on test_api 0.4.7, test >=1.17.11 requires test_api 0.4.3 or 0.4.4 or 0.4.5 or 0.4.6 or 0.4.7.
And because every version of flutter_test from sdk depends on test_api 0.4.2 and every version of coingecko_api depends on test ^1.17.12, flutter_test from sdk is incompatible with coingecko_api.
So, because portfolio depends on both coingecko_api any and flutter_test any from sdk, version solving failed.
pub finished with exit code 65
```

My flutter version is:
```

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
```

How can I solve this?

**Comment by yegor-pelykh** [comment] 2021-11-23 16:32
Hmm, it looks like it's not a package issue, something is wrong with flutter's / test package dependencies.

Could you try to upgrade flutter:
`flutter upgrade`

Also may be helpful to change channel for upgrade to dev/master:
`flutter channel [channel name]`

Does it help?

**Comment by yegor-pelykh** [comment] 2021-12-21 17:53
Hi @plibr

Is this problem still relevant for you?

**Comment by yegor-pelykh** [comment] 2021-12-30 14:28
Since this issue is not reproducible for me, and you have not confirmed its relevance, I have to close this issue.

**Closed as completed by yegor-pelykh** 2021-12-30 14:28 UTC
